<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>
<div class="form-container">
    <blockquote>
        <p class="text-primary">Usuario: <?php echo $this->result['ULastname'] ?>, <?php echo $this->result['UName'] ?></p>
    </blockquote>
    <form id="userForm" novalidate>
        <div class="form-group col-lg-4">
            <label for="UName">Nombre *</label>
            <label id="UName" name="UName" class="form-control" ><?php echo $this->result['UName']?></label>
        </div>
        <div class="form-group col-lg-4">
            <label for="ULastname">Apellido *</label>
            <label id="ULastname" name="ULastname" class="form-control" ><?php echo $this->result['ULastname']?></label>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="ULoginname">Nombre de Usuario *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-user"></label></span>
                <label id="ULoginname" name="ULoginname" class="form-control" ><?php echo $this->result['ULoginname']?></label>
            </div>
        </div>
        <div class="form-group col-lg-4">
            <label for="UPassword">Contraseña *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-lock"></label></span>
                <label name="UPassword" class="form-control" ><?php echo $this->result['UPassword']?></label>
            </div>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="UEmail">Email *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-envelope"></label></span>
                <label id="UEmail" name="UEmail" class="form-control" ><?php echo $this->result['UEmail']?></label>
            </div>
        </div>
        <div class="clearfix">

        </div>
        <br>
        <div class="btn-group">
            <button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url(array('module'=>$this->parameters['module'],'controller'=>$this->parameters['controller'], 'action' => 'edit', 'id' => $this->result['IDUser']), '', true)?>'" >Editar</button>
            <button type="button" class="btn btn-danger" onclick="location.href='<?php echo $this->url(array('module'=>$this->parameters['module'],'controller'=>$this->parameters['controller'], 'action' => 'delete', 'id' => $this->result['IDUser']), '', true)?>'" >Eliminar</button>
        </div>
    </form>
</div>