<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>
<div class="form-container">
    <blockquote>
        <?php if($this->title){?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-'.$this->icon.'"></label> ' : '' ;?> <?php echo $this->title?></p>
        <?php } ?>
        <?php if($this->description){?>
            <small><?php echo $this->description?></small>
        <?php } ?>
    </blockquote>
    <form id="userForm" method="post" novalidate>
        <div class="form-group col-lg-4">
            <label for="UName">Nombre *</label>
            <input value="<?php echo $this->result['UName']?>" type="text" id="UName" name="UName" class="form-control" placeholder="Nombre" data-validate="required">
        </div>
        <div class="form-group col-lg-4">
            <label for="ULastname">Apellido *</label>
            <input value="<?php echo $this->result['ULastname']?>" type="text" id="ULastname" name="ULastname" class="form-control" placeholder="Apellido" data-validate="required">
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="ULoginname">Nombre de Usuario *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-user"></label></span>
                <input value="<?php echo $this->result['ULoginname']?>" type="text" id="ULoginname" name="ULoginname" class="form-control" placeholder="Nombre de Usuario" data-validate="required">
            </div>
        </div>
        <div class="form-group col-lg-4">
            <label for="UPassword">Contraseña *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-lock"></label></span>
                <input type="password" id="UPassword" name="UPassword" class="form-control" placeholder="Contraseña" data-validate="custom_pass_eq">
            </div>
        </div>
        <div class="form-group col-lg-4">
            <label for="password2">Repetir Contraseña *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-lock"></label></span>
                <input type="password" id="password2" name="password2" class="form-control" placeholder="Repetir Contraseña" data-validate="custom_pass_eq">
            </div>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="UEmail">Email *</label>
            <div class="input-group">
                <span class="input-group-addon"><label class="glyphicon glyphicon-envelope"></label></span>
                <input value="<?php echo $this->result['UEmail']?>" ype="email" id="UEmail" name="UEmail" class="form-control" placeholder="Email" data-validate="required|email">
            </div>
        </div>
        <div class="clearfix">

        </div>
        <br>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /*<button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button>*/?>
            <button type="button" class="btn btn-danger" onclick='location.href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'index'), '', true)?>"'>Cancelar</button>
        </div>
    </form>
</div>