<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>
<div class="form-container">
    <blockquote>
        <?php if ($this->title) { ?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
            <small><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <form id="userForm" method="post" novalidate enctype="multipart/form-data"> 
        <div class="form-group col-lg-4">
            <label for="AColLeft">Columna Izquierda *</label>
            <textarea class="form-control" name="AColLeft" placeholder="Columna Izquierda" data-validate="required"><?php echo $this->result['AColLeft']?></textarea>
        </div>
        <div class="form-group col-lg-4">
            <label for="AColRight">Columna Derecha *</label>
            <textarea class="form-control" name="AColRight" placeholder="Columna Derecha" data-validate="required"><?php echo $this->result['AColRight']?></textarea>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="AColLeftEn">Columna Izquierda Inglés *</label>
            <textarea class="form-control" name="AColLeftEn" placeholder="Columna Izquierda Inglés" data-validate="required"><?php echo $this->result['AColLeftEn']?></textarea>
        </div>
        <div class="form-group col-lg-4">
            <label for="AColRightEn">Columna Derecha Inglés *</label>
            <textarea class="form-control" name="AColRightEn" placeholder="Columna Derecha Inglés" data-validate="required"><?php echo $this->result['AColRightEn']?></textarea>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="AFirm">Saludo *</label>
            <input type="text" id="AFirm" name="AFirm" class="form-control" maxlength="64" placeholder="Saludo" value="<?php echo $this->result['AFirm']?>" data-validate="required">
        </div>
        <div class="form-group col-lg-4">
            <label for="AFirmEn">Saludo Inglés*</label>
            <input type="text" id="AFirmEn" name="AFirmEn" class="form-control" maxlength="64" placeholder="Saludo Inglés" value="<?php echo $this->result['AFirmEn']?>" data-validate="required">
        </div>
        <div class="clearfix">

        </div>
        
        <br>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /* <button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button> */ ?>
           
        </div>
    </form>
</div>