<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>
<div class="form-container">
    <blockquote>
        <p class="text-primary">Nombre: <?php echo $this->result['RName'] ?></p>
    </blockquote>
    <form id="userForm" novalidate>
        <div class="form-group col-lg-4">
            <label for="SName">Nombre </label>
            <label id="RName" name="SName" class="form-control" ><?php echo $this->result['RName']?></label>
        </div>
        <div class="form-group col-lg-4">
            <label for="RNameEn">Nombre Inglés</label>
            <label id="RNameEn" name="RNameEn" class="form-control" ><?php echo $this->result['RNameEn']?></label>
        </div>
         <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="RTarifer">Precio por noche *</label>
            <br>
            <div class="col-xs-4">
                <div class="input-group ">
                    <span class="input-group-addon"><label class="glyphicon glyphicon-usd"></label></span>
                    <label id="RTarifer" name="RTarifer" class="form-control" placeholder="0.00" data-validate="required"><?php echo $this->result['RTarifer']?></label>
                </div>
            </div>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="RDescription">Descripción </label>
            <label id="RDescription" name="RDescription" class="form-control detail" ><?php echo nl2br($this->result['RDescription'])?></label>
        </div>
        <div class="form-group col-lg-4">
            <label for="RDescription">Descripción Inglés</label>
            <label id="RDescription" name="RDescription" class="form-control detail" ><?php echo nl2br($this->result['RDescriptionEn'])?></label>
        </div>
        <div class="clearfix">

        </div>
        <?php foreach ($this->images as $key => $result) { ?>
            <div class="box" id="<?php echo $result["IDImage"] ?>">
                <div class="form-group" style="float: left;">
                    <a style="margin-right: 50px;" title="<?php echo $result['IName'] ?>" class="popup" rel="prettyPhoto[]" href="<?php echo $this->baseUrl() . "/images/room/b_" . $result['IName'] ?>"><img style="border-radius: 4px;" src="<?php echo $this->baseUrl() . "/images/room/s_" . $result['IName'] ?>" /></a>
                    
                </div>
            </div>
        <?php } ?>
        <br>                <div class="clearfix"></div>

        <div class="btn-group">
            <button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url(array('module'=>$this->parameters['module'],'controller'=>$this->parameters['controller'], 'action' => 'edit', 'id' => $this->parameters['id']), '', true)?>'" >Editar</button>
            <button type="button" class="btn btn-danger" onclick="location.href='<?php echo $this->url(array('module'=>$this->parameters['module'],'controller'=>$this->parameters['controller'], 'action' => 'delete', 'id' => $this->parameters['id']), '', true)?>'" >Eliminar</button>
        </div>
    </form>
</div>