<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>
<div class="form-container">
    <blockquote>
        <?php if ($this->title) { ?>
            <p class="text-primary"><?php echo ($this->icon) ? '<label class="glyphicon glyphicon-' . $this->icon . '"></label> ' : ''; ?> <?php echo $this->title ?></p>
        <?php } ?>
        <?php if ($this->description) { ?>
            <small><?php echo $this->description ?></small>
        <?php } ?>
    </blockquote>
    <form id="userForm" method="post" novalidate enctype="multipart/form-data">
        <?php foreach ($this->results as $key => $result) { ?>
            <div class="box" id="<?php echo $result["IDRoom"] ?>">
                <input type="hidden" name="IDRoom[]" value="<?php echo $result["IDRoom"] ?>">
                <div class="form-group col-lg-4">
                    
                    <a style="margin-right: 50px;" class="popup" title="<?php echo $result['SName'] ?>" rel="prettyPhoto[]" href="<?php echo $this->baseUrl() . "/images/room/b_" . $result['IName'] ?>"><img src="<?php echo $this->baseUrl() . "/images/room/s_" . $result['IName'] ?>" /></a>
                    <label class="glyphicon glyphicon-arrow-up text-primary" onclick="up('<?php echo $result["IDRoom"] ?>')"></label> &nbsp; 
                    <label class="glyphicon glyphicon-arrow-down text-primary" onclick="down('<?php echo $result["IDRoom"] ?>')"></label>&nbsp;&nbsp;
                    <label ><?php echo $result["RName"] ?></label>
                </div>
                <div class="clearfix"></div>
            </div>
        <?php } ?>
        <br>
        <div class="btn-group">
            <button type="submit" name="submit" class="btn btn-primary" data-loading-text="Validando...">Guardar</button>
            <?php /* <button type="button" data-toggle="button" class="btn btn-info" data-rel="popover" data-content="asdasdasd" title="Información">Información</button> */ ?>
            <button type="button" class="btn btn-danger" onclick='location.href = "<?php echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'index'), '', true) ?>"'>Cancelar</button>
        </div>
    </form>
</div>
<script>
                        function up(id) {
                            var count = $('#userForm').find('div.box').length;
                            if (count > 1) {
                                var id_prev = ($('#' + id).prev().attr("id"));
                                if (id_prev != undefined) {
                                    $('#' + id).slideUp("normal", function() {
                                        $('#' + id).insertBefore('#' + id_prev);
                                    });
                                    $('#' + id).slideDown("normal");
                                }
                            }
                        }
                        function down(id) {
                            var count = $('#userForm').find('div.box').length;
                            if (count > 1) {
                                var id_next = ($('#' + id).next().attr("id"));
                                if (id_next != undefined) {
                                    $('#' + id).slideUp("normal", function() {
                                        $('#' + id).insertAfter('#' + id_next);
                                    });
                                    $('#' + id).slideDown("normal");

                                }
                            }
                        }
</script>