<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>
<div class="form-container">
    <blockquote>
        <p class="text-primary">Nombre: <?php echo $this->result['SName'] ?></p>
    </blockquote>
    <form id="userForm" novalidate>
        <div class="form-group col-lg-4">
            <label for="SName">Nombre </label>
            <label id="SName" name="SName" class="form-control" ><?php echo $this->result['SName']?></label>
        </div>
        <div class="form-group col-lg-4">
            <label for="SNameEn">Nombre Inglés</label>
            <label id="SNameEn" name="SNameEn" class="form-control" ><?php echo $this->result['SNameEn']?></label>
        </div>
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="ULastname">Descripción </label>
            <label id="ULastname" name="ULastname" class="form-control detail" ><?php echo nl2br($this->result['SText'])?></label>
        </div>
        <div class="form-group col-lg-4">
            <label for="ULastname">Descripción Inglés</label>
            <label id="ULastname" name="ULastname" class="form-control detail" ><?php echo nl2br($this->result['STextEn'])?></label>
        </div>
        
        <div class="clearfix">

        </div>
        <div class="form-group col-lg-4">
            <label for="SName">Imagen </label>
            <a class="popup"  rel="prettyPhoto[]" href="<?php echo $this->baseUrl()."/images/slider/b_".$this->result['SImage'] ?>">
            <img src="<?php echo $this->baseUrl()."/images/slider/m_".$this->result['SImage']?>" />
            </a>
        </div>
        <div class="clearfix">
        </div>
        
        <br>
        <div class="btn-group">
            <button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url(array('module'=>$this->parameters['module'],'controller'=>$this->parameters['controller'], 'action' => 'edit', 'id' => $this->parameters['id']), '', true)?>'" >Editar</button>
            <button type="button" class="btn btn-danger" onclick="location.href='<?php echo $this->url(array('module'=>$this->parameters['module'],'controller'=>$this->parameters['controller'], 'action' => 'delete', 'id' => $this->parameters['id']), '', true)?>'" >Eliminar</button>
        </div>
    </form>
</div>