<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
            <title><?php echo NAMECMS ?></title>
            <?php
            echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
            ?>
            <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.png'))
                    ->prependStylesheet($this->baseUrl() . '/css/bootstrap.css')
                    ->prependStylesheet($this->baseUrl() . '/css/cms.css')
                    ->prependStylesheet($this->baseUrl() . '/css/plus.css')
                    ->prependStylesheet($this->baseUrl() . "/css/jquery.lightbox.css")
                    ->prependStylesheet($this->baseUrl() . "/css/prettyPhoto.css");
            ?>       

    </head>
    <body>
        <nav class="navbar navbar-inverse main-navbar navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Mostrar navegación</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), '', true); ?>">-->
<!--                        <label class="glyphicon glyphicon-globe text-info"></label> <b class="text-info"><?php echo NAMECMS ?></b>-->
                <div class="marca_header">

                </div>
                <!--</a>-->
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">

                    <li>
                        <a data-rel="tooltipBottom" title="Ir a sección publíca" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), '', true); ?>">
                            <label class="glyphicon glyphicon-home"></label>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <?php echo $this->layout()->menu; ?>
                        </ul>
                    </li>
                </ul>                                      
                <?php echo $this->layout()->menuLogin; ?>
            </div><!-- /.navbar-collapse -->
        </nav>
        <!-- PANEL LEVEL 2 -->
        <!-- END PANEL LEVEL 2 -->
        <div class="content">
            <div class="progress progress-striped main-progressbar active">
                <div class="progress-bar progress-bar-<?php echo $this->statusBar ?>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">

                </div>
            </div>
            <div class="container">
                <nav class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url(array('module' => 'admin', 'controller' => $this->controller, 'action' => 'index'), '', true); ?>">
                            <?php echo $this->currentBrand ?>
                        </a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            <?php if ($this->currentIcon) { ?>
                                <li>
                                    <a data-rel="tooltipBottom" title="<?php echo $this->currentBrand ?>" href="<?php echo $this->url(array('module' => 'admin', 'controller' => $this->parameters['controller'], 'action' => 'index'), '', true); ?>">
                                        <label class="<?php echo $this->currentIcon ?>"></label>
                                    </a>
                                </li>
                            <?php } ?> 
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Opciones <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <!--<li role="presentation" class="dropdown-header">Acciones disponibles</li>-->
                                    <?php foreach ($this->actions as $action) { ?>
                                        <?php if ($action['type'] == 'link') { ?>
                                            <li>
                                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => $action['controller'], 'action' => $action['action']), '', true); ?>"><label class="text-primary glyphicon glyphicon-<?php echo $action['icon'] ?>"></label> <?php echo $action['label'] ?></a>
                                            </li>
                                        <?php } else { ?>                                    
                                            <li role="presentation" class="divider"></li>
                                        <?php } ?>
                                    <?php } ?>
                                </ul>
                            </li>
                        </ul>
                        <?php if ($this->enableSearch) { ?>
                            <form class="navbar-form navbar-right">
                                <div class="form-group">
                                    <input type="text" id="search" name="search" value="<?php echo $this->search ?>" class="form-control" placeholder="Ingrese palabras..." onkeyup="is_enter_search(event);" />
                                </div>

                                <button class="btn btn-default" onclick="search_user();">Buscar</button>
                            </form>

                        <?php } ?>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <?php //echo $this->layout()->subMenu;  ?>
                <?php echo $this->layout()->content; ?>
            </div>            

            <?php /* <h1><?php echo $this->layout()->titleMenu; ?></h1> */ ?>
            <?php // echo $this->layout()->titleSubMenu;  ?>

        </div>
        <nav class="navbar navbar-inverse" role="navigation">
            <ul class="nav navbar-nav pull-right">
                <div class="marca_footer">

                </div>
                <!--                <li>
                                    <p class="navbar-text text-info"><label class="glyphicon glyphicon-globe text-info"></label> <b class="text-info"><?php echo NAMECMS ?></b></p>
                                </li>-->
            </ul>        
        </nav>
    </body>
    <?php
    //POPUP
    //$this->headScript()->appendFile(HOST . $this->baseUrl() . "/js/jquery.js");
    ?>
    <?php
    $this->headScript()->prependFile($this->baseUrl() . '/js/bootstrap.validate.en.js', 'text/javascript');
    $this->headScript()->prependFile($this->baseUrl() . '/js/bootstrap.validate.js', 'text/javascript');
    $this->headScript()->prependFile($this->baseUrl() . '/js/popover.js', 'text/javascript');
    $this->headScript()->prependFile($this->baseUrl() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',));
    $this->headScript()->prependFile($this->baseUrl() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));
    $this->headScript()->prependFile($this->baseUrl() . '/js/bootstrap.min.js', 'text/javascript');
    $this->headScript()->prependFile($this->baseUrl() . '/js/jquery.js', 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.prettyPhoto.js");
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.lightbox.js");
    ;
    echo $this->headScript();
    ?>
    <script>
                                        function is_enter_search(code) {
                                            if (code.keyCode === 13)
                                                search_user();
                                        }

                                        function search_user() {
                                            location.href = '<?php echo $this->url(array('module' => $this->parameters['module'], 'controller' => $this->parameters['controller'], 'action' => 'index', 'page' => 1, 'search' => '')); ?>' + $('#search').val();
                                        }

                                        $(document).ready(function() {
                                            $("a.popup").prettyPhoto({animationSpeed: 'fast', slideshow: 10000, overlay_gallery: true});
                                            $("[data-rel=tooltipTop]").tooltip({placement: 'top', delay: {show: 500, hide: 100}});
                                            $("[data-rel=tooltipRight]").tooltip({placement: 'right', delay: {show: 500, hide: 100}});
                                            $("[data-rel=tooltipLeft]").tooltip({placement: 'left', delay: {show: 500, hide: 100}});
                                            $("[data-rel=tooltipBottom]").tooltip({placement: 'bottom', delay: {show: 500, hide: 100}});
                                            $("[data-rel=popover]").popover({title: 'Información', placement: 'top', delay: {show: 100, hide: 100}});

                                            $("[data-loading-text]").click(function() {
                                                var btn = $(this);
                                                btn.button('loading');
                                                setTimeout(function() {
                                                    btn.button('reset');
                                                }, 2000);
                                            });

                                            $('#<?php echo $this->formId ?>').bt_validate();
                                            $.bt_validate.method(
                                                    'custom_pass_eq',
                                                    function(value) {
                                                        return ($('#UPassword').val() === $('#password2').val());
                                                    },
                                                    "Las contraseñas no son iguales"
                                                    );

                                            $(".hideTooltip").click(
                                                    function() {
                                                        $(".tooltip").slideUp(300);
                                                    }
                                            );

                                        });
    </script>  
</html>
