<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
            <title><?php echo NAMECMS ?></title>
            <?php
            echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
            ?>
            <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.png'))
                    ->prependStylesheet($this->baseUrl() . '/css/bootstrap.css')
                    ->prependStylesheet($this->baseUrl() . '/css/cms_popup.css')
                    ->prependStylesheet($this->baseUrl() . '/css/plus.css')
                    ->prependStylesheet($this->baseUrl() . "/css/jquery.lightbox.css")
                    ->prependStylesheet($this->baseUrl() . "/css/prettyPhoto.css");
            ?>       
            <?php
    //POPUP
    $this->headScript()->appendFile(HOST . $this->baseUrl() . "/js/jquery.js");
   
    ;
    echo $this->headScript();
    ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse main-navbar" role="navigation" style="width: 100%; height: 50px;">
            <div class="navbar-header" style="width: 100%; height: 50px;">
                <div class="marca_header">
<label style=" padding-left: 150px;padding-top: 5px; font-size: 30px;" class="glyphicon glyphicon-camera text-primary"></label>
                </div>
            </div>
        </nav>
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
    
     
</html>
