<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
            <?php
            echo $this->headTitle($this->translate('Hotel el Nevado'))->setSeparator(' - ')->setAutoEscape(false);
            echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

            $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.js")
                    ->appendFile($this->baseUrl() . "/js/jquery.smint.js")
                    ->appendFile($this->baseUrl() . "/js/responsiveslides.js")
                    ->appendFile($this->baseUrl() . "/fancy/source/jquery.fancybox.js?v=2.1.5")
                    ->appendFile($this->baseUrl() . "/js/slider_config.js");
            $this->headScript()->appendFile($this->baseUrl() . "/js/grayscale.js");
            echo $this->headScript();

            $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.png'))
                    ->prependStylesheet($this->baseUrl() . '/css/style_20201211.css')
                    ->prependStylesheet($this->baseUrl() . '/fancy/source/jquery.fancybox.css?v=2.1.5')
                    ->prependStylesheet($this->baseUrl() . "/css/slider.css");
            echo $this->headLink();
            ?>
            <link href='http://fonts.googleapis.com/css?family=Snippet' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
                <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script>
                <script type="text/javascript">
                    function initialize() {
                        var mapDiv = document.getElementById('map-canvas');
                        var map = new google.maps.Map(mapDiv, {
                            center: new google.maps.LatLng(-32.895803, -68.828488),
                            zoom: 14,
                            mapTypeId: google.maps.MapTypeId.ROADMAP
                        });
                        var marker = new google.maps.Marker({
                            map: map,
                            position: new google.maps.LatLng(-32.895803, -68.828488),
                            draggable: false
                        });
                        var infoWindow = new google.maps.InfoWindow({
                            position: new google.maps.LatLng(-32.895803, -68.828488),
                            Padding: 10,
                            minWidth: 200,
                            content: '<div >'
                                    + '<table>'
                                    + '    <tr>'
                                    + '      <td rowspan=2>'
                                    + '          <img src="<?php echo $this->baseUrl() . "/imgs/logo_gray.png" ?>" width="130">'
                                    + '      </td>'
                                    + '    </tr>'
                                    + '<table>'
                                    + '</div>'
                        });
                        infoWindow.open(map);
                    }
                    google.maps.event.addDomListener(window, 'load', initialize);
                </script> -->
                <script type="text/javascript">


                    $(document).ready(function() {
                        //  $("a.popup").prettyPhoto({animationSpeed: 'fast', slideshow: 10000, overlay_gallery: true});
                        $('.subMenu').smint({
                            'scrollSpeed': 1000
                        });
                        $('.fancybox').fancybox({
                            width: 720,
                            heigth: 500,
                            autoHeight: false,
                        });
//                        $(".s3 .image img").grayscale('50');
                    });</script>
                </head>

                <body onload="setTimeout(function() {
                            window.scrollTo(0, 1)
                        }, 100);">
                    <div id="fb-root"></div>
                    <script>(function(d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id))
                            return;
                        js = d.createElement(s);
                        js.id = id;
                        js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=538554892849925";
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                    <a href="https://api.whatsapp.com/send?phone=+5492616554911&text=Hola%21%20Quisiera%20m%C3%A1s%20informaci%C3%B3n%20sobre%20el%20hotel." class="float" target="_blank">
<i class="fa fa-whatsapp my-float"></i>
</a>
                    <div class="wrap">
                        <div class="subMenu" >
                            <div class="inner">
                                <a href="#" id="sTop" class="subNavBtn"><?php echo ($this->parameters["lang"] == "en") ? 'Home' : 'Inicio'; ?></a> 
                                <a href="#" id="s2" class="subNavBtn"><?php echo ($this->parameters["lang"] == "en") ? 'About Us' : 'Quienes Somos'; ?></a>
                                <a href="#" id="s3" class="subNavBtn"><?php echo ($this->parameters["lang"] == "en") ? 'Rooms' : 'Habitaciones'; ?></a>
                                <a href="#" id="s4" class="subNavBtn"><?php echo ($this->parameters["lang"] == "en") ? 'Rate/Reserves' : 'Tarifario/Reservas'; ?></a>
                                <a href="#" id="s5" class="subNavBtn"><?php echo ($this->parameters["lang"] == "en") ? 'Location/Contact' : 'Ubicación/Contacto'; ?></a>
                                
                            </div>
                        </div>
                        <div class="section sTop" style=" background:url(<?php echo $this->baseUrl() . "/imgs/" . $this->bg; ?>) #313131 center top no-repeat;">
                            <div class="inner">
                                <a href="#" ><img src="<?php echo $this->baseUrl() . "/imgs/marca_hotel_el_nevado.png"; ?>"></a>
                                <div class="facebook">
                                    <a title="Español" href="<?php echo $this->url(array('lang' => 'es')); ?>"><img src="<?php echo $this->baseUrl() . "/imgs/esp.png"; ?>" /></a><a title="English" href="<?php echo $this->url(array('lang' => 'en')); ?>"><img src="<?php echo $this->baseUrl() . "/imgs/eng.png"; ?>" /></a>
<!--<a title="Facebook" href="http://www.facebook.com"><img src="<?php //echo $this->baseUrl() . "/imgs/facebook.png";    ?>" /></a>-->
                                </div>
                                <div class="facebook_header">
                                                   <div class="fb-like" data-href="https://www.facebook.com/pages/Hotel-el-Nevado/351196881651217?fref=ts" data-width="50" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>

                                </div>
                            </div>
                            <br class="clear">
                        </div>
<?php echo $this->layout()->content; ?>
                        <div class="footer">
                            <p><?php echo $this->contact["CFooter" . $this->sufix] ?></p>
                        </div>

                    </div>  
                    
                </body>
                </html>
